### ISSUE TITLE
Stopped working?

### ISSUE THREAD

**Issue by ivanjeremic** [CharlesStover/use-force-update#17]
This hook stopped working, No Component Updates are triggered anymore. Any chance to fix this?

**Comment by CharlesStover** [comment]
We'll need more information than this. What version of React are you using? Do you have a minimal reproduction?

This hook has a full test suite to validate its functionality pre-publication.

**Comment by CharlesStover** [comment]
Closing this as not enough info and no other mentions of this by other users. I can only conclude its an implementation issue in your application and not the hook itself, since the code did not change and has thorough unit testing.
