### ISSUE TITLE
Less complex implementation

### ISSUE THREAD

**Issue by donavon** [CharlesStover/use-force-update#2]
wouldn't this work just as well? none of the `max` nonsense.

```js
const useForceUpdate = () => {
  const [, setIt] = useState(false);
  return () => setIt(it => !it);
};
```

**Comment by CharlesStover** [comment]
I don't see why not! I've heard that you can just call setIt with no parameters, and it will always cause a re-renders (no shallow comparisons for updating), but I haven't had time to test that.

**Comment by donavon** [comment]
It works! So I've ended up here.

```js
const useForceUpdate = () => useState()[1];
```

**Comment by phpnode** [comment]
also the stuff to prevent integer overflow in the current implementation is _probably_ unnecessary. If your app rerendered 60x per second it would take 4760 years to overflow.
